auto : true
permalink : /:title/
exclude : ['sass', 'config.rb', 'README.md']

title : WordPress Wednesdays
description : The best WordPress links every Wednesday.
url : http://wordpresswednesdays.co
author :
  firstName : Nelson
  lastName : Joyce
  jobTitle : LeadIn
  url : http://LeadIn.com
  email : nellyvan@gmail.com
  github : gnelsonj
  linkedIn : gnelsonj
  twitter : nelsonjoyce
  twitterId : 216396668
  dribbble : nelsonjoyce
  googlePlus : 116388594856737469980
  feedBurner : nelsonjoyce
  location : Boston MA